Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'tradersdiary.in'. You may need to add 'tradersdiary.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: feeds_personalinformation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tradghsd/srshti/feeds/views.py", line 19, in home_page
    return render(request, 'home_page.html', context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: feeds_personalinformation
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: feeds_personalinformation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tradghsd/srshti/feeds/views.py", line 19, in home_page
    return render(request, 'home_page.html', context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: feeds_personalinformation
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: feeds_personalinformation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tradghsd/srshti/feeds/views.py", line 19, in home_page
    return render(request, 'home_page.html', context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: feeds_personalinformation
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /wp-cron.php
Not Found: /wp-cron.php
Not Found: /wp-admin/admin-ajax.php
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /wp-login.php
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /favicon.ico
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'srshti.co.in'. You may need to add 'srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /favicon.ico
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /.well-known/pki-validation/FA4AC54B3613EC1C45BF0E01CF71504D.txt
Not Found: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tradghsd/srshti/feeds/views.py", line 19, in home_page
    return render(request, 'home_page.html', context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/fields/files.py", line 63, in url
    self._require_file()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/fields/files.py", line 40, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'image' attribute has no file associated with it.
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /None
Not Found: /favicon.ico
Not Found: /None
Not Found: /None
Invalid HTTP_HOST header: 'mail.srshti.co.in'. You may need to add 'mail.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /favicon.ico
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Invalid HTTP_HOST header: 'www.srshti.co.in'. You may need to add 'www.srshti.co.in' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
Not Found: /favicon.ico
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Traceback (most recent call last):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/tradghsd/srshti/passenger_wsgi.py", line 1, in <module>
    from portfolio.wsgi import application
  File "/home/tradghsd/srshti/portfolio/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tradghsd/virtualenv/srshti/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /favicon.ico
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
Not Found: /static/images/fonts/Agustina.21f233e1.woff
Not Found: /Assets/img/15.jpg
